name: Python checks 🐍 (gitverse)
on:
  push:
  pull_request:

jobs:
  python-checks:
    runs-on: ubuntu-cloud-runner
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install poetry
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          export PATH="$POETRY_HOME/bin:$PATH"
          pip install poetry==2.1.4
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH

      - name: Poetry config disable virtual environments
        run: |
          poetry config  virtualenvs.create false

      - name: Install dependencies
        run: poetry sync --no-root --no-interaction --no-ansi

      - name: Run Black check
        run: black --check --diff ./

      - name: Run ruff check --diff
        run: ruff check --diff ./

      - name: Run ruff check
        run: ruff check ./

      - name: Run mypy
        run: mypy bot-app

      # Создаю .env файл из шаблона для тестов
      - name: Setup .env file
        run: cp bot-app/.env.template bot-app/.env

  run-tests:
    runs-on: ubuntu-cloud-runner
    needs:
      - run-checks
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install poetry
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          export PATH="$POETRY_HOME/bin:$PATH"
          pip install poetry==2.1.4
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH

      - name: Poetry config disable virtual environments
        run: |
          poetry config  virtualenvs.create false

      - name: Install dependencies
        run: poetry sync --no-root --no-interaction --no-ansi

      - name: Run tests
        run: poetry run pytest
