# Название action
name: Deploy to Server

# Основной триггер
on:
  workflow_run:
    workflows:
      - "Python checks 🐍"
    branches:
      - master
    types:
      - completed

jobs:
  deploy: # Название работы
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' && !github.event.act }}
    runs-on: ubuntu-latest   # Где будет выполняться (виртуальная Ubuntu)
    steps:
      # Деплой через SSH если тесты прошли
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1  # Используем готовый экшен для SSH подключения
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |                                # Набор команд для выполнения на сервере
            /home/${{ secrets.SERVER_USER }}/deploy.sh

      # Уведомление в тг, если предыдущие шаги не сработали
      - name: Send Telegram notification on deploy failure
        if: failure()
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚨 Ошибка деплоя tasker-bot"

      # Уведомление в тг, если предыдущие шаги сработали
      - name: Send Telegram notification on deploy success
        if: success()
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Бот tasker-bot успешно обновлен"
