# Название action
name: Deploy to Server

# Основной триггер
on:
  push: # При пуше в репозиторий
    branches:
      - master             # Только если пуш в ветку "master"

jobs:
  deploy: # Название работы
    runs-on: ubuntu-latest   # Где будет выполняться (виртуальная Ubuntu)

    steps:
      # Клонирую репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Устанавливаю Docker Compose
      - name: Install Docker Compose v2
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Собираю контейнеры
      - name: Build docker-compose services
        run: docker-compose build bot

      # Создаю .env файл из шаблона для тестов
      - name: Setup .env file
        run: cp .env.template .env

      # Запускаю тесты внутри контейнера
      - name: Run tests in bot container
        run: docker-compose run --rm bot poetry run pytest -s

      # Деплой через SSH если тесты прошли
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6  # Используем готовый экшен для SSH подключения
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |                                # Набор команд для выполнения на сервере
            /home/github_deployer/deploy.sh        # Запуск скрипта

      # Уведомление в тг, если предыдущие шаги не сработали
      - name: Send Telegram notification on deploy failure
        if: failure()
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚨 Ошибка деплоя tasker-bot"

      # Уведомление в тг, если предыдущие шаги сработали
      - name: Send Telegram notification on deploy success
        if: success()
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Бот tasker-bot успешно обновлен"
